namespace ScreenSaver.Examples.AfterDarkAquarium
{
    public enum eAquariumKeys
    {
        SeaFloor,
        Bubbles,
        BubblesFlipped,
        ButterflyFish,
        ButterflyFishFlipped,
        GuppyFish,
        GuppyFishFlipped,
        SeahorseFish,
        SeahorseFishFlipped,
        JellyFish,
        JellyFishFlipped,
        MinnowFish,
        MinnowFishFlipped,
        RedFish,
        RedFishFlipped,
        StripedFish,
        StripedFishFlipped,
        AngelFish,
        AngelFishFlipped,
        FlounderFish,
        FlounderFishFlipped,
        Scuba,
        ScubaFlipped,
    }
}